version: '3.9'

services:
  app:
    build: .
    ports:
      - "9001:8000"
    volumes:
      - ./:/var/www
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"   # optional for host access
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_db
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
